@endpoint = http://localhost:5050/api/v1/bikes

 

###
# @name postABike

POST {{endpoint}} HTTP/1.1
content-type: application/json
x-api-key: blahblah

{ "bikeName": "to be deleted",
    "type": "Mountain",
    "pricePerHour": 5,
    "pricePerDay": 20,
    "available": true,
    "description": "great jumping over small hills",
    "colour": "black",
    "brand": "green"
}

###

@newBike = {{postABike.response.body._id}}

###
GET  {{endpoint}} HTTP/3.0 
content-type: application/json
x-api-key: blahblah 

 

### 

GET {{endpoint}}/{{newBike}} HTTP/3.0
content-type: application/json
x-api-key: blahblah
### 

 

DELETE  {{endpoint}}/6ac8cc294e7343dfb56ac829 HTTP/3.0 
content-type: application/json
x-api-key: blahblah

 

### 

 

###
PUT {{endpoint}}/6ac8cc294e7343dfb56ac829 HTTP/1.1
Content-Type: application/json
x-api-key: blahblah

{
    "bikeName": "Trek Marlin 8",
    "type": "Mountain",
    "pricePerHour": 5,
    "pricePerDay": 20,
    "available": true,
    "description": "great jumping over small hills",
    "colour": "black",
    "brand": "Trek"
}